### ISSUE TITLE
Actions in Release workflow are still using Node.js 12

### ISSUE THREAD

**Issue by Varneon** [vrchat-community/template-package#1]
![image](https://user-images.githubusercontent.com/26690821/214229576-6251e9f8-2b2c-4518-90ec-d991318df93f.png)

https://github.com/vrchat-community/template-package/blob/2d0924df345bba94f8776572942b5a453f22fe2e/.github/workflows/release.yml#L22

https://github.com/notiz-dev/github-action-json-property/blob/7c8cf5cc36eb85d8d287a8086a39dac59628eb31/action.yml#L10

https://github.com/vrchat-community/template-package/blob/2d0924df345bba94f8776572942b5a453f22fe2e/.github/workflows/release.yml#L49

https://github.com/softprops/action-gh-release/blob/1e07f4398721186383de40550babbdf2b84acfc5/action.yml#L56

Both actions have newer releases available that have upgraded to using Node.js 16

**Comment by momo-the-monster** [comment]
Fixed, thanks!
