### ISSUE TITLE
New repositories default to read only access for workflows resulting in error in Release workflow

### ISSUE THREAD

**Issue by Varneon** [vrchat-community/template-package#2]
New repositories _(created in 2023?)_ default the workflow permissions to `Read repository contents permission` _(previously `Read and write permission`)_.

This setting can be found under: `Repository` > `Settings` > `Code and automation` > `Actions` > `General` > `Workflow permissions`:

![image](https://user-images.githubusercontent.com/26690821/214232092-6e7bc274-7f11-4ccf-8b55-5ab36bd5205d.png)

Unless this option is manually set to `Read and write permission`, the Release workflow will result in an error due to insufficient permissions when attempting to create a new release:

![image](https://user-images.githubusercontent.com/26690821/214230284-19c3cd05-4b27-4118-952c-26349eece8f0.png)

**Comment by Spokeek** [comment]
I used this template recently and it seem to work as expected.

This is was fixed in a commit made in the end of March : https://github.com/vrchat-community/template-package/commit/10fd190261fb427b9baad054dee39db5027e9cfb

I suggest you try it again. Else i can look with you.

**Comment by momo-the-monster** [comment]
Closing since this is fixed now, thanks for the report and the follow-up, @Varneon and @Spokeek!
