### ISSUE TITLE
Build Listing GitHub Action fails on 'Build Package Version Listing' step with 'NullReferenceException'

### ISSUE THREAD

**Issue by dustuu** [vrchat-community/template-package#9]
I'm having an issue with the `build-listing.yml` GitHub Action from the VPM Package Template repo (https://github.com/vrchat-community/template-package/blob/main/.github/workflows/build-listing.yml)

Whenever it runs, it throws a `NullReferenceException` on the `Build Package Version Listing` step, which uses Nuke.

I've tried recreating packages from the provided template a few times, and reached this same result every time. So, I've created a minimal reproducible repo here: https://github.com/dustuu/NukeException

You can see the job failing here: https://github.com/dustuu/NukeException/actions/runs/5184710843/jobs/9343872908#step:5:46

The only changes I have made from the template repo are following the steps outlined in the provided readme file to import and convert an existing package. For the purposes of this example, I have used only a single empty U# script as my target.

Thanks in advance for any guidance you can provide.

**Comment by dustuu** [comment]
Just in case the job logs aren't visible to external users, here is a screenshot as well:
![image](https://github.com/vrchat-community/template-package/assets/101824882/14637275-98ce-4fea-ad41-dae582386f60)

**Comment by Faxmashine** [comment]
Your `package.json` includes the following line:
https://github.com/dustuu/NukeException/blob/323abbd5b66e64fabbc670bc346ffd2781f65eaf/Packages/com.dustuu.nuke-exception/package.json#L12
```json
"localPath": "C:\\Users\\conno\\Source\\Repos\\dustuu\\NukeException\\Packages\\com.dustuu.nuke-exception",
```
You may not want to include a local path in your packages. Can you remove it and see what happens?
If that doesn't help, I'd be happy to help reproduce the issue.

For reference, here's a simple example listing that runs successfully: https://github.com/Faxmashine/MyAmazingPackage/tree/main

**Comment by dustuu** [comment]
@Faxmashine  Thanks for the quick response!

I actually previously removed the `localPath` property from my `package.json` while trying to fix this issue, but saw it had no effect. So, I kept it in this version in an attempt to create a minimal repo with as few changes from the default state as possible (since the VPM Package Maker tool actually includes this `localPath` property by default when generating `package.json` files).

But just to be sure, I removed it again [here](https://github.com/dustuu/NukeException/commit/287d86eff30e484e4c2fcf868e246c683f6b33b7) which unfortunately still [failed](https://github.com/dustuu/NukeException/actions/runs/5190505917).

However, I took a look at the `package.json` [you provided](https://github.com/Faxmashine/MyAmazingPackage/blob/main/Packages/com.fax.amazing-package/package.json) and made a second commit [here](https://github.com/dustuu/NukeException/commit/4d5397f79273a861bc4fda434a62dc6d6fb168eb) to try and match my `package.json` as closely as possible to your structure.

This one actually [worked](https://github.com/dustuu/NukeException/actions/runs/5190542958)! I was able to isolate the important change [here](https://github.com/dustuu/NukeException/commit/fae96c469c273519189025c4ba4a5038158b7f47): it turns out that the `author` property is actually required in the `package.json` file, and not including it causes [this error](https://github.com/dustuu/NukeException/actions/runs/5190646508).

However, the VPM Package Maker tool currently does not include this required `author` property in generated `package.json` files. Here’s an example of a freshly generated `package.json` file:

```
{
  "name": "com.dustuu.test-package-maker-tool",
  "displayName": "com.dustuu.test-package-maker-tool",
  "version": "0.0.1",
  "description": "Describe this Package",
  "dependencies": {},
  "gitDependencies": {},
  "vpmDependencies": {
    "com.vrchat.udonsharp": "1.1.8"
  },
  "legacyFolders": {},
  "legacyFiles": {},
  "localPath": "C:\\Users\\conno\\Source\\Repos\\dustuu\\NukeException\\Packages\\com.dustuu.test-package-maker-tool"
}
```

The tool currently does not include the `author` property, but does include the `localPath` property, which may be unnecessary. If my understanding is correct, this means all packages currently created with the VPM Package Maker tool will fail when used with [this GitHub Action](https://github.com/vrchat-community/template-package/blob/main/.github/workflows/build-listing.yml). The `author` property currently must be added manually to avoid this.

I would be happy to make a pull request on the [VPM Package Maker repo](https://github.com/vrchat-community/vpm-package-maker) that fixes these issues, but it appears that this repo was archived last year. Is it alright to open a pull request on this archived repo, or is there a better place?

Thanks again for your help!

**Comment by Faxmashine** [comment]
Thank you @dustuu for further investigating the issue! We'll look into the issue ourselves and see if we can fix the package maker.

**Comment by dustuu** [comment]
This issue has been fixed now that the package maker includes author configuration fields.
